# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "44b95e366cc7dcb7b0eec8a0e28745c3"
application_url = "https://enrolled-pharmacies-constructed-comment.trycloudflare.com"
embedded = true
name = "product-management"
handle = "product-management-35"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "carts/update" ]
  uri = "/webhooks/app/carts_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_cart_transforms"

[auth]
redirect_urls = [
  "https://enrolled-pharmacies-constructed-comment.trycloudflare.com/auth/callback",
  "https://enrolled-pharmacies-constructed-comment.trycloudflare.com/auth/shopify/callback",
  "https://enrolled-pharmacies-constructed-comment.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[[extensions]]
name = "Cart Validation Embed"
type = "theme_app_extension"
metafields = [ ]
